# Goal
# data[0] = 0.0 -> joint target
# data[0] = 1.0 -> pose target
# data[0] = 2.0 -> gripper command
float64[] data

---
# Result
bool success
string error_code
string error_description

---
# Feedback
string state        # e.g. "RECEIVED", "PLANNING", "EXECUTING", "DONE"
float32 progress    # 0.0 - 1.0 (you can keep it simple)
